### ISSUE TITLE
problems about training

### ISSUE THREAD

**Issue by Serge-weihao** [layumi/Seg-Uncertainty#11]
why you train your model in stage 1 and 3 with 100000 iterations, but choose 25000th iteration for finetunning and final evaluation?

**Comment by layumi** [comment]
@Serge-weihao 
Early-stopping is to prevent the model overfitting to the source dataset, which is widely-used in previous works. You may check the https://github.com/RoyalVane/CLAN

**Comment by Serge-weihao** [comment]
does it mean the process after 25000th is useless?

**Comment by layumi** [comment]
@Serge-weihao 
Yes. You may skip the training.
