### ISSUE TITLE
About data loading

### ISSUE THREAD

**Issue by BinhuiXie** [layumi/Seg-Uncertainty#12]
Hello, thank for sharing the great work. I have a quick question. I find that ''random scale'' and ''mirror'' are used for preprocessing data, which is a little different from previous works. 

- So, for what reason did you adopt these strategies?

- Have you conducted experiments to verify how much performance improvement they bring?

Thanks!

**Comment by layumi** [comment]
Hi @BinhuiXie 
Sorry for the late response. 
I have not evaluated these strategies. In general, the improvement is limited, which does not affect our conclusion.
