### ISSUE TITLE
Prediction variance and Prediction confidence

### ISSUE THREAD

**Issue by SnowdenLee** [layumi/Seg-Uncertainty#21]
Hello, 

could you maybe explain the difference between prediction variance and prediction Confidence? In the paper, Figure 5 visualizes both, but I'm not sure how do you calculate them. I assume the KL term divergence is used as variance, then how to get the confidence?

Thanks in advance.

**Comment by layumi** [comment]
Hi @SnowdenLee 
The prediction score is the confidence. You can directly print the prediction score of the highest class among 0~1 after softmax.
