### ISSUE TITLE
load state dict error

### ISSUE THREAD

**Issue by valencebond** [layumi/Seg-Uncertainty#24]
When conducting experiments of stage 1 training,  state dicts of self.G model is inconsistent with the pretrained model in 'http://vllab.ucmerced.edu/ytsai/CVPR18/DeepLab_resnet_pretrained_init-f81d91e8.pth'. For example, key of state dict of self.G is 'layer5.conv2d_list.0.0.weight' and 'layer6.bottleneck.0.se.0.weight', but key of the pretrained model is 'layer5.conv2d_list.0.weight' and there is no module 'layer6.bottleneck.0.se.0.weight'. Should I set the strict as False in load_state_dict()?

**Comment by valencebond** [comment]
Besides, due to the "Scale" in the key of pretrained model weight, [code](https://github.com/layumi/Seg-Uncertainty/blob/0184b422393da3ff903dda8025b3b1d0cb6921de/trainer_ms.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L91) need to change to discard the "Scale".  I am curious, no one has ever encountered such a problem?

**Comment by layumi** [comment]
I do not meet such problem before. 
It seems to be the model change from UC Merced.  @valencebond  
Could you try the https://github.com/wasidennis/AdaptSegNet and check the model weight? 

Actually, I modified this repo from the AdaptSegNet (published by UC Merced ) and the weights are also from UC Merced villa.

**Comment by valencebond** [comment]
Sorry ，it was my fault. Due to network reasons, I downloaded the HTTP file and saved it local. So the logic of if-else changes.
