### ISSUE TITLE
tabular data/ noisy instances 

### ISSUE THREAD

**Issue by nazaretl** [layumi/Seg-Uncertainty#26]
Hi,
thanks for sharing your implementation. I have two questions about it:

1.	Does it also work on tabular data?
2.	Is it possible to identify the noisy instances (return the noisy IDs or the clean set)?

Thanks!

**Comment by layumi** [comment]
Hi @nazaretl 

Thanks a lot for your attention on our works. 

1. I have not tried it. You may try it. I think it could work. 
2. I think it is possible to identify the noisy data, if the prediction is not consistent between two classifiers.

**Comment by nazaretl** [comment]
thank you!
