### ISSUE TITLE
can not get good performance

### ISSUE THREAD

**Issue by panzhang0212** [layumi/Seg-Uncertainty#4]
Hi, I have some problems
1.for your release model:
stage 1 model (SE_GN_batchsize2_1024x512_pp_ms_me0_classbalance7_kl0.1_lr2_drop0.1_seg0.5), I test this model using your code, the mIoU is only 38.07, much lower than 45.5(stage 1 miou in MRNet paper).  stage2 model(1280x640_restore_ft_GN_batchsize9_512x256_pp_ms_me0_classbalance7_kl0_lr1_drop0.2_seg0.5_BN_80_255_0.8_Noaug) is 50.34 , which is same as the report result in second paper.
2. train result
I use your released stage 1 model to generate pseudo label, then train stage 2, However, the performance is low: 43.89 for 25000.pth, 42.69 for 50000.pth, 41.98 for 100000.pth, much lower than the result in your paper. And I do not change any code except variable DATA_DIRECTORY

**Comment by layumi** [comment]
![image](https://user-images.githubusercontent.com/8390471/83320726-88f3f800-a28d-11ea-81c0-d9dc711255ff.png)
![image](https://user-images.githubusercontent.com/8390471/83320734-9ad59b00-a28d-11ea-9a6f-8184798a430d.png)

As shown in the figure, I just re-run the test code. 
```
python evaluate_cityscapes.py --restore-from ./snapshots/SE_GN_batchsize2_1024x512_pp_ms_me0_classbalance7_kl0.1_lr2_drop0.1_seg0.5/GTA5_25000.pth --batchsize 2
```
 And my test result is 45.5

**Comment by layumi** [comment]
![image](https://user-images.githubusercontent.com/8390471/83320823-5f879c00-a28e-11ea-879b-0346c714934c.png)
Could you check the md5sum first? Thanks a lot.

**Comment by panzhang0212** [comment]
![snipaste_20200530_141453](https://user-images.githubusercontent.com/30363822/83321101-fa2cae80-a27f-11ea-9617-ed207de366c2.png)
your release de model is GTA50000.pth

**Comment by panzhang0212** [comment]
![snipaste_20200530_141453](https://user-images.githubusercontent.com/30363822/83321101-fa2cae80-a27f-11ea-9617-ed207de366c2.png)
your release de model is GTA50000.pth

**Comment by panzhang0212** [comment]
Could you clone the code and released SE_GN_batchsize2_1024x512_pp_ms_me0_classbalance7_kl0.1_lr2_drop0.1_seg0.5/GTA5_50000.pth, then try the test code again? thanks

**Comment by layumi** [comment]
It is my fault. I have update the download link  https://drive.google.com/file/d/1smh1sbOutJwhrfK8dk-tNvonc0HLaSsw/view?usp=sharing

**Comment by panzhang0212** [comment]
Thanks your help!
